CREATE UNIQUE INDEX IF NOT EXISTS UX_a16a88_Id ON sedm.IDEAEvent(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_d153ae_Id ON sedm.StudentIEP(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_1314b5_Id ON sedm.StudentIEPAccommodationCollection(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_0f858c_Id ON sedm.StudentIEPDisabilityCollection(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_5453a5_Id ON sedm.StudentIEPGoal(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_524fcd_Id ON sedm.StudentIEPServiceDelivery(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_d0ad1a_Id ON sedm.StudentIEPServicePrescription(Id);

