IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'tracked_changes_tpdm')
EXEC sys.sp_executesql N'CREATE SCHEMA [tracked_changes_tpdm]'
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[ApplicantProfile]'))
CREATE TABLE [tracked_changes_tpdm].[ApplicantProfile]
(
       OldApplicantProfileIdentifier [NVARCHAR](32) NOT NULL,
       NewApplicantProfileIdentifier [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_ApplicantProfile PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[Application]'))
CREATE TABLE [tracked_changes_tpdm].[Application]
(
       OldApplicantProfileIdentifier [NVARCHAR](32) NOT NULL,
       OldApplicationIdentifier [NVARCHAR](20) NOT NULL,
       OldEducationOrganizationId [BIGINT] NOT NULL,
       NewApplicantProfileIdentifier [NVARCHAR](32) NULL,
       NewApplicationIdentifier [NVARCHAR](20) NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_Application PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[ApplicationEvent]'))
CREATE TABLE [tracked_changes_tpdm].[ApplicationEvent]
(
       OldApplicantProfileIdentifier [NVARCHAR](32) NOT NULL,
       OldApplicationEventTypeDescriptorId [INT] NOT NULL,
       OldApplicationEventTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldApplicationEventTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldApplicationIdentifier [NVARCHAR](20) NOT NULL,
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEventDate [DATE] NOT NULL,
       OldSequenceNumber [INT] NOT NULL,
       NewApplicantProfileIdentifier [NVARCHAR](32) NULL,
       NewApplicationEventTypeDescriptorId [INT] NULL,
       NewApplicationEventTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewApplicationEventTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewApplicationIdentifier [NVARCHAR](20) NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEventDate [DATE] NULL,
       NewSequenceNumber [INT] NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_ApplicationEvent PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[Candidate]'))
CREATE TABLE [tracked_changes_tpdm].[Candidate]
(
       OldCandidateIdentifier [NVARCHAR](32) NOT NULL,
       NewCandidateIdentifier [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_Candidate PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[CandidateEducatorPreparationProgramAssociation]'))
CREATE TABLE [tracked_changes_tpdm].[CandidateEducatorPreparationProgramAssociation]
(
       OldBeginDate [DATE] NOT NULL,
       OldCandidateIdentifier [NVARCHAR](32) NOT NULL,
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldProgramName [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorId [INT] NOT NULL,
       OldProgramTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewBeginDate [DATE] NULL,
       NewCandidateIdentifier [NVARCHAR](32) NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewProgramName [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorId [INT] NULL,
       NewProgramTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_CandidateEducatorPreparationProgramAssociation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[CandidateRelationshipToStaffAssociation]'))
CREATE TABLE [tracked_changes_tpdm].[CandidateRelationshipToStaffAssociation]
(
       OldCandidateIdentifier [NVARCHAR](32) NOT NULL,
       OldStaffUSI [INT] NOT NULL,
       OldStaffUniqueId [NVARCHAR](32) NOT NULL,
       NewCandidateIdentifier [NVARCHAR](32) NULL,
       NewStaffUSI [INT] NULL,
       NewStaffUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_CandidateRelationshipToStaffAssociation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[Certification]'))
CREATE TABLE [tracked_changes_tpdm].[Certification]
(
       OldCertificationIdentifier [NVARCHAR](60) NOT NULL,
       OldNamespace [NVARCHAR](255) NOT NULL,
       NewCertificationIdentifier [NVARCHAR](60) NULL,
       NewNamespace [NVARCHAR](255) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_Certification PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[CertificationExam]'))
CREATE TABLE [tracked_changes_tpdm].[CertificationExam]
(
       OldCertificationExamIdentifier [NVARCHAR](60) NOT NULL,
       OldNamespace [NVARCHAR](255) NOT NULL,
       NewCertificationExamIdentifier [NVARCHAR](60) NULL,
       NewNamespace [NVARCHAR](255) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_CertificationExam PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[CertificationExamResult]'))
CREATE TABLE [tracked_changes_tpdm].[CertificationExamResult]
(
       OldCertificationExamDate [DATE] NOT NULL,
       OldCertificationExamIdentifier [NVARCHAR](60) NOT NULL,
       OldNamespace [NVARCHAR](255) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewCertificationExamDate [DATE] NULL,
       NewCertificationExamIdentifier [NVARCHAR](60) NULL,
       NewNamespace [NVARCHAR](255) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_CertificationExamResult PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[CredentialEvent]'))
CREATE TABLE [tracked_changes_tpdm].[CredentialEvent]
(
       OldCredentialEventDate [DATE] NOT NULL,
       OldCredentialEventTypeDescriptorId [INT] NOT NULL,
       OldCredentialEventTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldCredentialEventTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldCredentialIdentifier [NVARCHAR](60) NOT NULL,
       OldStateOfIssueStateAbbreviationDescriptorId [INT] NOT NULL,
       OldStateOfIssueStateAbbreviationDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldStateOfIssueStateAbbreviationDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewCredentialEventDate [DATE] NULL,
       NewCredentialEventTypeDescriptorId [INT] NULL,
       NewCredentialEventTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewCredentialEventTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewCredentialIdentifier [NVARCHAR](60) NULL,
       NewStateOfIssueStateAbbreviationDescriptorId [INT] NULL,
       NewStateOfIssueStateAbbreviationDescriptorNamespace [NVARCHAR](255) NULL,
       NewStateOfIssueStateAbbreviationDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_CredentialEvent PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[EducatorPreparationProgram]'))
CREATE TABLE [tracked_changes_tpdm].[EducatorPreparationProgram]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldProgramName [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorId [INT] NOT NULL,
       OldProgramTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewProgramName [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorId [INT] NULL,
       NewProgramTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_EducatorPreparationProgram PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[Evaluation]'))
CREATE TABLE [tracked_changes_tpdm].[Evaluation]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_Evaluation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[EvaluationElement]'))
CREATE TABLE [tracked_changes_tpdm].[EvaluationElement]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationElementTitle [NVARCHAR](255) NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationElementTitle [NVARCHAR](255) NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_EvaluationElement PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[EvaluationElementRating]'))
CREATE TABLE [tracked_changes_tpdm].[EvaluationElementRating]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationDate [DATETIME2](7) NOT NULL,
       OldEvaluationElementTitle [NVARCHAR](255) NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationDate [DATETIME2](7) NULL,
       NewEvaluationElementTitle [NVARCHAR](255) NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_EvaluationElementRating PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[EvaluationObjective]'))
CREATE TABLE [tracked_changes_tpdm].[EvaluationObjective]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_EvaluationObjective PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[EvaluationObjectiveRating]'))
CREATE TABLE [tracked_changes_tpdm].[EvaluationObjectiveRating]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationDate [DATETIME2](7) NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationDate [DATETIME2](7) NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_EvaluationObjectiveRating PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[EvaluationRating]'))
CREATE TABLE [tracked_changes_tpdm].[EvaluationRating]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationDate [DATETIME2](7) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationDate [DATETIME2](7) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_EvaluationRating PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[FieldworkExperience]'))
CREATE TABLE [tracked_changes_tpdm].[FieldworkExperience]
(
       OldBeginDate [DATE] NOT NULL,
       OldFieldworkIdentifier [NVARCHAR](64) NOT NULL,
       OldStudentUSI [INT] NOT NULL,
       OldStudentUniqueId [NVARCHAR](32) NOT NULL,
       NewBeginDate [DATE] NULL,
       NewFieldworkIdentifier [NVARCHAR](64) NULL,
       NewStudentUSI [INT] NULL,
       NewStudentUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_FieldworkExperience PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[FieldworkExperienceSectionAssociation]'))
CREATE TABLE [tracked_changes_tpdm].[FieldworkExperienceSectionAssociation]
(
       OldBeginDate [DATE] NOT NULL,
       OldFieldworkIdentifier [NVARCHAR](64) NOT NULL,
       OldLocalCourseCode [NVARCHAR](60) NOT NULL,
       OldSchoolId [BIGINT] NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldSectionIdentifier [NVARCHAR](255) NOT NULL,
       OldSessionName [NVARCHAR](60) NOT NULL,
       OldStudentUSI [INT] NOT NULL,
       OldStudentUniqueId [NVARCHAR](32) NOT NULL,
       NewBeginDate [DATE] NULL,
       NewFieldworkIdentifier [NVARCHAR](64) NULL,
       NewLocalCourseCode [NVARCHAR](60) NULL,
       NewSchoolId [BIGINT] NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewSectionIdentifier [NVARCHAR](255) NULL,
       NewSessionName [NVARCHAR](60) NULL,
       NewStudentUSI [INT] NULL,
       NewStudentUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_FieldworkExperienceSectionAssociation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[FinancialAid]'))
CREATE TABLE [tracked_changes_tpdm].[FinancialAid]
(
       OldAidTypeDescriptorId [INT] NOT NULL,
       OldAidTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldAidTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldBeginDate [DATE] NOT NULL,
       OldStudentUSI [INT] NOT NULL,
       OldStudentUniqueId [NVARCHAR](32) NOT NULL,
       NewAidTypeDescriptorId [INT] NULL,
       NewAidTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewAidTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewBeginDate [DATE] NULL,
       NewStudentUSI [INT] NULL,
       NewStudentUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_FinancialAid PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[Goal]'))
CREATE TABLE [tracked_changes_tpdm].[Goal]
(
       OldAssignmentDate [DATE] NOT NULL,
       OldGoalTitle [NVARCHAR](255) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewAssignmentDate [DATE] NULL,
       NewGoalTitle [NVARCHAR](255) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_Goal PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[OpenStaffPositionEvent]'))
CREATE TABLE [tracked_changes_tpdm].[OpenStaffPositionEvent]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEventDate [DATE] NOT NULL,
       OldOpenStaffPositionEventTypeDescriptorId [INT] NOT NULL,
       OldOpenStaffPositionEventTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldOpenStaffPositionEventTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldRequisitionNumber [NVARCHAR](20) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEventDate [DATE] NULL,
       NewOpenStaffPositionEventTypeDescriptorId [INT] NULL,
       NewOpenStaffPositionEventTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewOpenStaffPositionEventTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewRequisitionNumber [NVARCHAR](20) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_OpenStaffPositionEvent PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[PerformanceEvaluation]'))
CREATE TABLE [tracked_changes_tpdm].[PerformanceEvaluation]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_PerformanceEvaluation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[PerformanceEvaluationRating]'))
CREATE TABLE [tracked_changes_tpdm].[PerformanceEvaluationRating]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_PerformanceEvaluationRating PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[ProfessionalDevelopmentEvent]'))
CREATE TABLE [tracked_changes_tpdm].[ProfessionalDevelopmentEvent]
(
       OldNamespace [NVARCHAR](255) NOT NULL,
       OldProfessionalDevelopmentTitle [NVARCHAR](60) NOT NULL,
       NewNamespace [NVARCHAR](255) NULL,
       NewProfessionalDevelopmentTitle [NVARCHAR](60) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_ProfessionalDevelopmentEvent PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[ProfessionalDevelopmentEventAttendance]'))
CREATE TABLE [tracked_changes_tpdm].[ProfessionalDevelopmentEventAttendance]
(
       OldAttendanceDate [DATE] NOT NULL,
       OldNamespace [NVARCHAR](255) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldProfessionalDevelopmentTitle [NVARCHAR](60) NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewAttendanceDate [DATE] NULL,
       NewNamespace [NVARCHAR](255) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewProfessionalDevelopmentTitle [NVARCHAR](60) NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_ProfessionalDevelopmentEventAttendance PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[QuantitativeMeasure]'))
CREATE TABLE [tracked_changes_tpdm].[QuantitativeMeasure]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationElementTitle [NVARCHAR](255) NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldQuantitativeMeasureIdentifier [NVARCHAR](64) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationElementTitle [NVARCHAR](255) NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewQuantitativeMeasureIdentifier [NVARCHAR](64) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_QuantitativeMeasure PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[QuantitativeMeasureScore]'))
CREATE TABLE [tracked_changes_tpdm].[QuantitativeMeasureScore]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationDate [DATETIME2](7) NOT NULL,
       OldEvaluationElementTitle [NVARCHAR](255) NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldQuantitativeMeasureIdentifier [NVARCHAR](64) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationDate [DATETIME2](7) NULL,
       NewEvaluationElementTitle [NVARCHAR](255) NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewQuantitativeMeasureIdentifier [NVARCHAR](64) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_QuantitativeMeasureScore PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[RecruitmentEvent]'))
CREATE TABLE [tracked_changes_tpdm].[RecruitmentEvent]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEventDate [DATE] NOT NULL,
       OldEventTitle [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEventDate [DATE] NULL,
       NewEventTitle [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_RecruitmentEvent PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[RecruitmentEventAttendance]'))
CREATE TABLE [tracked_changes_tpdm].[RecruitmentEventAttendance]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEventDate [DATE] NOT NULL,
       OldEventTitle [NVARCHAR](50) NOT NULL,
       OldRecruitmentEventAttendeeIdentifier [NVARCHAR](32) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEventDate [DATE] NULL,
       NewEventTitle [NVARCHAR](50) NULL,
       NewRecruitmentEventAttendeeIdentifier [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_RecruitmentEventAttendance PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[RubricDimension]'))
CREATE TABLE [tracked_changes_tpdm].[RubricDimension]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationElementTitle [NVARCHAR](255) NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldRubricRating [INT] NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationElementTitle [NVARCHAR](255) NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewRubricRating [INT] NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_RubricDimension PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[StaffEducatorPreparationProgramAssociation]'))
CREATE TABLE [tracked_changes_tpdm].[StaffEducatorPreparationProgramAssociation]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldProgramName [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorId [INT] NOT NULL,
       OldProgramTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldProgramTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldStaffUSI [INT] NOT NULL,
       OldStaffUniqueId [NVARCHAR](32) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewProgramName [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorId [INT] NULL,
       NewProgramTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewProgramTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewStaffUSI [INT] NULL,
       NewStaffUniqueId [NVARCHAR](32) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_StaffEducatorPreparationProgramAssociation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[SurveyResponsePersonTargetAssociation]'))
CREATE TABLE [tracked_changes_tpdm].[SurveyResponsePersonTargetAssociation]
(
       OldNamespace [NVARCHAR](255) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSurveyIdentifier [NVARCHAR](60) NOT NULL,
       OldSurveyResponseIdentifier [NVARCHAR](60) NOT NULL,
       NewNamespace [NVARCHAR](255) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSurveyIdentifier [NVARCHAR](60) NULL,
       NewSurveyResponseIdentifier [NVARCHAR](60) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_SurveyResponsePersonTargetAssociation PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[SurveySectionAggregateResponse]'))
CREATE TABLE [tracked_changes_tpdm].[SurveySectionAggregateResponse]
(
       OldEducationOrganizationId [BIGINT] NOT NULL,
       OldEvaluationDate [DATETIME2](7) NOT NULL,
       OldEvaluationElementTitle [NVARCHAR](255) NOT NULL,
       OldEvaluationObjectiveTitle [NVARCHAR](50) NOT NULL,
       OldEvaluationPeriodDescriptorId [INT] NOT NULL,
       OldEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTitle [NVARCHAR](50) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorId [INT] NOT NULL,
       OldPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSchoolYear [SMALLINT] NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSurveyIdentifier [NVARCHAR](60) NOT NULL,
       OldSurveySectionTitle [NVARCHAR](255) NOT NULL,
       OldTermDescriptorId [INT] NOT NULL,
       OldTermDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldTermDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       NewEducationOrganizationId [BIGINT] NULL,
       NewEvaluationDate [DATETIME2](7) NULL,
       NewEvaluationElementTitle [NVARCHAR](255) NULL,
       NewEvaluationObjectiveTitle [NVARCHAR](50) NULL,
       NewEvaluationPeriodDescriptorId [INT] NULL,
       NewEvaluationPeriodDescriptorNamespace [NVARCHAR](255) NULL,
       NewEvaluationPeriodDescriptorCodeValue [NVARCHAR](50) NULL,
       NewEvaluationTitle [NVARCHAR](50) NULL,
       NewNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTitle [NVARCHAR](50) NULL,
       NewPerformanceEvaluationTypeDescriptorId [INT] NULL,
       NewPerformanceEvaluationTypeDescriptorNamespace [NVARCHAR](255) NULL,
       NewPerformanceEvaluationTypeDescriptorCodeValue [NVARCHAR](50) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSchoolYear [SMALLINT] NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSurveyIdentifier [NVARCHAR](60) NULL,
       NewSurveySectionTitle [NVARCHAR](255) NULL,
       NewTermDescriptorId [INT] NULL,
       NewTermDescriptorNamespace [NVARCHAR](255) NULL,
       NewTermDescriptorCodeValue [NVARCHAR](50) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_SurveySectionAggregateResponse PRIMARY KEY CLUSTERED (ChangeVersion)
)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[tracked_changes_tpdm].[SurveySectionResponsePersonTargetAssociation]'))
CREATE TABLE [tracked_changes_tpdm].[SurveySectionResponsePersonTargetAssociation]
(
       OldNamespace [NVARCHAR](255) NOT NULL,
       OldPersonId [NVARCHAR](32) NOT NULL,
       OldSourceSystemDescriptorId [INT] NOT NULL,
       OldSourceSystemDescriptorNamespace [NVARCHAR](255) NOT NULL,
       OldSourceSystemDescriptorCodeValue [NVARCHAR](50) NOT NULL,
       OldSurveyIdentifier [NVARCHAR](60) NOT NULL,
       OldSurveyResponseIdentifier [NVARCHAR](60) NOT NULL,
       OldSurveySectionTitle [NVARCHAR](255) NOT NULL,
       NewNamespace [NVARCHAR](255) NULL,
       NewPersonId [NVARCHAR](32) NULL,
       NewSourceSystemDescriptorId [INT] NULL,
       NewSourceSystemDescriptorNamespace [NVARCHAR](255) NULL,
       NewSourceSystemDescriptorCodeValue [NVARCHAR](50) NULL,
       NewSurveyIdentifier [NVARCHAR](60) NULL,
       NewSurveyResponseIdentifier [NVARCHAR](60) NULL,
       NewSurveySectionTitle [NVARCHAR](255) NULL,
       Id uniqueidentifier NOT NULL,
       ChangeVersion bigint NOT NULL,
       Discriminator [NVARCHAR](128) NULL,
       CreateDate DateTime2 NOT NULL DEFAULT (getutcdate()),
       CONSTRAINT PK_SurveySectionResponsePersonTargetAssociation PRIMARY KEY CLUSTERED (ChangeVersion)
)
